name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: cmake -B build
    - name: make
      run: cmake --build build
    - name: make check
      run: cmake --build build --target test
    - name: make distcheck
      run: cmake --build build --target package_source
